/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unal.vista;

import com.unal.RedFlix.SpringContext;
import com.unal.RedFlix.modelos.Repositorio.UsuarioRepositorio;
import com.unal.RedFlix.modelos.Usuario;
import java.awt.Component;
import java.awt.EventQueue;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

/**
 *
 * @author USER
 */
@SpringBootApplication
@ComponentScan("com.unal.RedFlix")
@EntityScan("com.unal.RedFlix.modelos")
@EnableJpaRepositories("com.unal.RedFlix.modelos.Repositorio")
public class VentanaApp extends javax.swing.JFrame {

    UsuarioRepositorio repoUsuario;

    /**
     * Creates new form VentanaApp
     */
    public VentanaApp() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setRepoUsuario(UsuarioRepositorio repositorio) {
        this.repoUsuario = repositorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelUsuario = new javax.swing.JPanel();
        NombreLabel = new javax.swing.JLabel();
        NombreTexto = new javax.swing.JFormattedTextField();
        ApellidoLabel = new javax.swing.JLabel();
        ApellidoTexto = new javax.swing.JFormattedTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTexto = new javax.swing.JFormattedTextField();
        CelularLabel = new javax.swing.JLabel();
        FechaNacimientoLabel = new javax.swing.JLabel();
        CelularTexto = new javax.swing.JFormattedTextField();
        FechaNacimientoTexto = new javax.swing.JFormattedTextField();
        AliasLabel = new javax.swing.JLabel();
        AliasTexto = new javax.swing.JFormattedTextField();
        ContraseñaLabel = new javax.swing.JLabel();
        ContraseñaTexto = new javax.swing.JPasswordField();
        Contraseña2Texto = new javax.swing.JPasswordField();
        Contraseña2Label = new javax.swing.JLabel();
        jPanelPelicula = new javax.swing.JPanel();
        jLabelTituloP = new javax.swing.JLabel();
        jLabelResumen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneResumen = new javax.swing.JTextPane();
        jTextFieldTituloP = new javax.swing.JFormattedTextField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JFormattedTextField();
        jLabelDirector = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JFormattedTextField();
        jPanelSerie = new javax.swing.JPanel();
        jLabelTituloS = new javax.swing.JLabel();
        jTextFieldTituloS = new javax.swing.JFormattedTextField();
        jLabelNTemporadas = new javax.swing.JLabel();
        jTextFieldTemporadas = new javax.swing.JFormattedTextField();
        jLabelNEpisodios = new javax.swing.JLabel();
        jTextFieldEpisodios = new javax.swing.JFormattedTextField();
        AccionSelector = new javax.swing.JComboBox<>();
        EjectarAccionBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedFlix App");
        setBackground(new java.awt.Color(153, 204, 255));
        setLocation(new java.awt.Point(0, 0));

        jPanelUsuario.setBackground(new java.awt.Color(236, 236, 255));
        jPanelUsuario.setNextFocusableComponent(AliasTexto);

        NombreLabel.setText("Nombre");

        NombreTexto.setNextFocusableComponent(ApellidoTexto);

        ApellidoLabel.setText("Apellido");

        ApellidoTexto.setNextFocusableComponent(CelularTexto);

        EmailLabel.setText("E-mail");

        EmailTexto.setNextFocusableComponent(NombreTexto);

        CelularLabel.setText("Celular");

        FechaNacimientoLabel.setText("Fecha de Nacimiento");

        CelularTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        CelularTexto.setNextFocusableComponent(FechaNacimientoTexto);

        FechaNacimientoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        FechaNacimientoTexto.setNextFocusableComponent(ContraseñaTexto);
        FechaNacimientoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaNacimientoTextoActionPerformed(evt);
            }
        });

        AliasLabel.setText("Alias");

        AliasTexto.setNextFocusableComponent(EmailTexto);

        ContraseñaLabel.setText("Contraseña");

        ContraseñaTexto.setNextFocusableComponent(ContraseñaTexto);

        Contraseña2Texto.setNextFocusableComponent(AccionSelector);

        Contraseña2Label.setText("Confirmacion");

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addComponent(CelularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addComponent(AliasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AliasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmailTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(ApellidoTexto)))
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContraseñaLabel)
                                    .addComponent(Contraseña2Label))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CelularTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(NombreTexto))
                                    .addComponent(Contraseña2Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContraseñaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaNacimientoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApellidoLabel))
                                .addGap(18, 18, 18)
                                .addComponent(FechaNacimientoTexto)))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AliasLabel)
                    .addComponent(AliasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel)
                    .addComponent(NombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoLabel)
                    .addComponent(ApellidoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelularLabel)
                    .addComponent(CelularTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaNacimientoLabel)
                    .addComponent(FechaNacimientoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaLabel)
                    .addComponent(ContraseñaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contraseña2Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contraseña2Label))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        NombreLabel.getAccessibleContext().setAccessibleDescription("");
        Contraseña2Label.getAccessibleContext().setAccessibleName("");

        jTabbedPane.addTab("Usuario", jPanelUsuario);

        jLabelTituloP.setText("Titulo");

        jLabelResumen.setText("Resumen:");

        jScrollPane1.setViewportView(jTextPaneResumen);

        jLabelAnio.setText("Año");

        jTextFieldAnio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabelDirector.setText("Director");

        javax.swing.GroupLayout jPanelPeliculaLayout = new javax.swing.GroupLayout(jPanelPelicula);
        jPanelPelicula.setLayout(jPanelPeliculaLayout);
        jPanelPeliculaLayout.setHorizontalGroup(
            jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeliculaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResumen)
                    .addGroup(jPanelPeliculaLayout.createSequentialGroup()
                        .addGroup(jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTituloP)
                            .addComponent(jLabelAnio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTituloP)
                            .addGroup(jPanelPeliculaLayout.createSequentialGroup()
                                .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabelDirector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDirector)))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanelPeliculaLayout.setVerticalGroup(
            jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeliculaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloP)
                    .addComponent(jTextFieldTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnio)
                    .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirector)
                    .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Pelicula", jPanelPelicula);

        jLabelTituloS.setText("Titulo");

        jLabelNTemporadas.setText("Numero de temporadas");

        jTextFieldTemporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTemporadasActionPerformed(evt);
            }
        });

        jLabelNEpisodios.setText("Numero de episodios");

        javax.swing.GroupLayout jPanelSerieLayout = new javax.swing.GroupLayout(jPanelSerie);
        jPanelSerie.setLayout(jPanelSerieLayout);
        jPanelSerieLayout.setHorizontalGroup(
            jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSerieLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSerieLayout.createSequentialGroup()
                        .addComponent(jLabelTituloS)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTituloS, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelSerieLayout.createSequentialGroup()
                        .addGroup(jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNTemporadas)
                            .addComponent(jLabelNEpisodios))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelSerieLayout.setVerticalGroup(
            jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSerieLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloS)
                    .addComponent(jTextFieldTituloS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNTemporadas)
                    .addComponent(jTextFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNEpisodios)
                    .addComponent(jTextFieldEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Serie", jPanelSerie);

        AccionSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una acción", "Agregar", "Buscar", "Actualizar", "Borrar" }));
        AccionSelector.setNextFocusableComponent(EjectarAccionBoton);
        AccionSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AccionSelectorItemStateChanged(evt);
            }
        });
        AccionSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionSelectorActionPerformed(evt);
            }
        });

        EjectarAccionBoton.setText("Ejecutar");
        EjectarAccionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjectarAccionBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AccionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EjectarAccionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EjectarAccionBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaNacimientoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaNacimientoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaNacimientoTextoActionPerformed

    private void jTextFieldTemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTemporadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTemporadasActionPerformed

    private void AccionSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccionSelectorActionPerformed

    private void AccionSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AccionSelectorItemStateChanged
        if (evt.getStateChange() != java.awt.event.ItemEvent.SELECTED) {
            return;
        }
        String seleccion = AccionSelector.getSelectedItem().toString();
        switch (seleccion) {
            case "Agregar":
                ActivarCampos(true);
                break;
            case "Buscar":
                ActivarCampos(false);
                AliasTexto.setEnabled(true); 
                break;
            case "Actualizar":
                ActivarCampos(true);
                break;
            case "Borrar":
                ActivarCampos(false);
                AliasTexto.setEnabled(true); 
                break;
            default:
                ActivarCampos(false);
                break;
        }
    }//GEN-LAST:event_AccionSelectorItemStateChanged

    private void EjectarAccionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjectarAccionBotonActionPerformed
        switch (AccionSelector.getSelectedItem().toString()) {
            case "Agregar":
                agregarUsuario();
                break;
            case "Buscar":
                String text = AliasTexto.getText();
                if (!text.isEmpty()) {
                    Optional<Usuario> result = repoUsuario.findById(text);
                    if (result.isPresent()) {
                        Usuario userFound = result.get();
                        System.out.println(userFound.toString());
                        ApellidoTexto.setText(userFound.getApellidos());
                        NombreTexto.setText(userFound.getNombres());
                        EmailTexto.setText(userFound.getEmail());
                        CelularTexto.setText(userFound.getCelular());
                        //TO-DO 
                    } else {
                        String alertaText = "No se ha encontradro un usuario con ese el alias " + text;
                        System.out.println(alertaText);
                        JOptionPane.showMessageDialog(rootPane, alertaText);
                    }

                } else {
                    String alertaText = "Querido usuario parece que se olvidó colocar el alias a buscar";
                    System.out.println(alertaText);
                    JOptionPane.showMessageDialog(rootPane, alertaText);
                }
                break;
            case "Actualizar":
                System.out.println("C");
                break;
            case "Borrar":
                System.out.println("D");
                break;
        }
    }//GEN-LAST:event_EjectarAccionBotonActionPerformed

    private void ActivarCampos(boolean bloqueo){
        AliasTexto.setEnabled(bloqueo);
        NombreTexto.setEnabled(bloqueo);
        ApellidoLabel.setEnabled(bloqueo);
        AliasTexto.setEnabled(bloqueo);
        FechaNacimientoTexto.setEnabled(bloqueo);
        CelularTexto.setEnabled(bloqueo);
        ContraseñaTexto.setEnabled(bloqueo);
        Contraseña2Texto.setEnabled(bloqueo);
    }
    
    private void agregarUsuario() {
        Usuario nuevoUsuario = new Usuario();

        javax.swing.JFormattedTextField[] camposObligatorios = {AliasTexto,
            NombreTexto, ApellidoTexto, jTextFieldContrasenia};

        nuevoUsuario.setAlias(AliasTexto.getText());
        nuevoUsuario.setApellidos(ApellidoTexto.getText());
        nuevoUsuario.setNombres(NombreTexto.getText());
        nuevoUsuario.setCelular(CelularTexto.getText());
        nuevoUsuario.setContraseña(jTextFieldContrasenia.getText());
        nuevoUsuario.setEmail(EmailTexto.getText());

        for (javax.swing.JFormattedTextField txt : camposObligatorios) {
            if (txt.getText().isEmpty()) {
                String alertaText = "No se han ingresado los campos requeridos";
                JOptionPane.showMessageDialog(rootPane, alertaText);
                return;
            }
        }

        try {
            repoUsuario.save(nuevoUsuario);
            System.out.println("Usuario Agregado correctamente");
        } catch (Exception e) {
            String alertaText = "Ocurrió un error al guardar";
            JOptionPane.showMessageDialog(rootPane, alertaText, "Error en el ingreso de "
                    + "un nuevo usuario", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void preparacionAgregar() {
        javax.swing.JPanel panelActual = (javax.swing.JPanel) jTabbedPane.getSelectedComponent();
        for (Component c : panelActual.getComponents()) {
            //System.out.println(c.getClass().getSimpleName());
            if (c.getClass().getSimpleName().equalsIgnoreCase("JFormattedTextField")) {
                c.setEnabled(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccionSelector;
    private javax.swing.JLabel AliasLabel;
    private javax.swing.JFormattedTextField AliasTexto;
    private javax.swing.JLabel ApellidoLabel;
    private javax.swing.JFormattedTextField ApellidoTexto;
    private javax.swing.JLabel CelularLabel;
    private javax.swing.JFormattedTextField CelularTexto;
    private javax.swing.JLabel Contraseña2Label;
    private javax.swing.JPasswordField Contraseña2Texto;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JPasswordField ContraseñaTexto;
    private javax.swing.JButton EjectarAccionBoton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JFormattedTextField EmailTexto;
    private javax.swing.JLabel FechaNacimientoLabel;
    private javax.swing.JFormattedTextField FechaNacimientoTexto;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JFormattedTextField NombreTexto;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelNEpisodios;
    private javax.swing.JLabel jLabelNTemporadas;
    private javax.swing.JLabel jLabelResumen;
    private javax.swing.JLabel jLabelTituloP;
    private javax.swing.JLabel jLabelTituloS;
    private javax.swing.JPanel jPanelPelicula;
    private javax.swing.JPanel jPanelSerie;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JFormattedTextField jTextFieldAnio;
    private javax.swing.JFormattedTextField jTextFieldDirector;
    private javax.swing.JFormattedTextField jTextFieldEpisodios;
    private javax.swing.JFormattedTextField jTextFieldTemporadas;
    private javax.swing.JFormattedTextField jTextFieldTituloP;
    private javax.swing.JFormattedTextField jTextFieldTituloS;
    private javax.swing.JTextPane jTextPaneResumen;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        ConfigurableApplicationContext ctx = SpringApplication.run(VentanaApp.class, args);

        EventQueue.invokeLater(() -> {
            SpringContext context = new SpringContext();
            context.setApplicationContext(ctx);
            VentanaApp ex = ctx.getBean(VentanaApp.class);
            ex.setVisible(true);
            ex.setRepoUsuario(ctx.getBean(UsuarioRepositorio.class));
        });
    }
}
