/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unal.vista;

import com.unal.RedFlix.SpringContext;
import com.unal.RedFlix.modelos.Repositorio.UsuarioRepositorio;
import com.unal.RedFlix.modelos.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

/**
 *
 * @author USER
 */
@SpringBootApplication
@ComponentScan("com.unal.RedFlix")
@EntityScan("com.unal.RedFlix.modelos")
@EnableJpaRepositories("com.unal.RedFlix.modelos.Repositorio")
public class VentanaApp extends javax.swing.JFrame {

    UsuarioRepositorio repoUsuario;

    /**
     * Creates new form VentanaApp
     */
    public VentanaApp() {
        this.getContentPane().setBackground(new Color(102, 102, 255));
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setRepoUsuario(UsuarioRepositorio repositorio) {
        this.repoUsuario = repositorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsuario = new javax.swing.JPanel();
        NombreLabel = new javax.swing.JLabel();
        NombreTexto = new javax.swing.JFormattedTextField();
        ApellidoLabel = new javax.swing.JLabel();
        ApellidoTexto = new javax.swing.JFormattedTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTexto = new javax.swing.JFormattedTextField();
        CelularLabel = new javax.swing.JLabel();
        FechaNacimientoLabel = new javax.swing.JLabel();
        CelularTexto = new javax.swing.JFormattedTextField();
        FechaNacimientoTexto = new javax.swing.JFormattedTextField();
        AliasLabel = new javax.swing.JLabel();
        AliasTexto = new javax.swing.JFormattedTextField();
        ContraseñaLabel = new javax.swing.JLabel();
        ContraseñaTexto = new javax.swing.JPasswordField();
        Contraseña2Texto = new javax.swing.JPasswordField();
        Contraseña2Label = new javax.swing.JLabel();
        EjectarAccionBoton = new javax.swing.JButton();
        AccionSelector = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedFlix App");
        setBackground(new java.awt.Color(0, 0, 255));
        setLocation(new java.awt.Point(0, 0));

        jPanelUsuario.setBackground(new java.awt.Color(236, 236, 255));
        jPanelUsuario.setNextFocusableComponent(AliasTexto);

        NombreLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        NombreLabel.setText("Nombre");

        NombreTexto.setToolTipText("Los nombres pertenecientes al usuario");
        NombreTexto.setNextFocusableComponent(ApellidoTexto);

        ApellidoLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ApellidoLabel.setText("Apellido");

        ApellidoTexto.setToolTipText("Los apellidos pertenecientes al usuario");
        ApellidoTexto.setNextFocusableComponent(CelularTexto);

        EmailLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        EmailLabel.setText("E-mail");

        EmailTexto.setNextFocusableComponent(NombreTexto);

        CelularLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        CelularLabel.setText("Celular");

        FechaNacimientoLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        FechaNacimientoLabel.setText("Fecha de Nacimiento");

        CelularTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        CelularTexto.setNextFocusableComponent(FechaNacimientoTexto);

        FechaNacimientoTexto.setNextFocusableComponent(ContraseñaTexto);
        FechaNacimientoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaNacimientoTextoActionPerformed(evt);
            }
        });

        AliasLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        AliasLabel.setText("Alias");

        AliasTexto.setToolTipText("Contiene el alias que sera usado como identificador para el usuario");
        AliasTexto.setNextFocusableComponent(EmailTexto);

        ContraseñaLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ContraseñaLabel.setText("Contraseña");

        ContraseñaTexto.setNextFocusableComponent(ContraseñaTexto);

        Contraseña2Texto.setNextFocusableComponent(AccionSelector);

        Contraseña2Label.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        Contraseña2Label.setText("Confirmacion");

        EjectarAccionBoton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        EjectarAccionBoton.setText("Ejecutar");
        EjectarAccionBoton.setToolTipText("Ejecuta la accion actualmente mostrada por el selector");
        EjectarAccionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjectarAccionBotonActionPerformed(evt);
            }
        });

        AccionSelector.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        AccionSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una acción", "Agregar", "Buscar", "Actualizar", "Borrar" }));
        AccionSelector.setNextFocusableComponent(EjectarAccionBoton);
        AccionSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AccionSelectorItemStateChanged(evt);
            }
        });
        AccionSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CelularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addComponent(AliasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AliasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaLabel)
                            .addComponent(Contraseña2Label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CelularTexto)
                                .addComponent(NombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Contraseña2Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(AccionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EjectarAccionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FechaNacimientoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ApellidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaNacimientoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApellidoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AliasLabel)
                    .addComponent(AliasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel)
                    .addComponent(NombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoLabel)
                    .addComponent(ApellidoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelularLabel)
                    .addComponent(CelularTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaNacimientoLabel)
                    .addComponent(FechaNacimientoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaLabel)
                    .addComponent(ContraseñaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Contraseña2Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AccionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EjectarAccionBoton))
                    .addComponent(Contraseña2Label))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        NombreLabel.getAccessibleContext().setAccessibleDescription("");
        Contraseña2Label.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaNacimientoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaNacimientoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaNacimientoTextoActionPerformed

    private void AccionSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccionSelectorActionPerformed

    private void AccionSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AccionSelectorItemStateChanged
        if (evt.getStateChange() != java.awt.event.ItemEvent.SELECTED) {
            return;
        }
        String seleccion = AccionSelector.getSelectedItem().toString();
        switch (seleccion) {
            case "Agregar":
                ActivarCampos(true);
                break;
            case "Buscar":
                ActivarCampos(false);
                AliasTexto.setEnabled(true);
                break;
            case "Actualizar":
                ActivarCampos(true);
                break;
            case "Borrar":
                ActivarCampos(false);
                AliasTexto.setEnabled(true);
                break;
            default:
                ActivarCampos(false);
                break;
        }
    }//GEN-LAST:event_AccionSelectorItemStateChanged

    private void EjectarAccionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjectarAccionBotonActionPerformed
        switch (AccionSelector.getSelectedItem().toString()) {
            case "Agregar":
                if (VerificarContraseña()) {
                    establecerUsuario();
                } else {
                    ContraseñaTexto.setBackground(Color.red);
                }
                break;
            case "Buscar":
                String text = AliasTexto.getText();
                if (!text.isEmpty()) {
                    buscarUsuario(text);
                } else {
                    String alertaText = "Querido usuario parece que se olvidó colocar el alias a buscar";
                    System.out.println(alertaText);
                    JOptionPane.showMessageDialog(rootPane, alertaText);
                }
                break;
            case "Actualizar":
                if (VerificarContraseña()) {
                    establecerUsuario();
                } else {
                    ContraseñaTexto.setBackground(Color.red);
                }
                break;
            case "Borrar":
                Usuario usuario = new Usuario();
                usuario.setAlias(AliasTexto.getText());
                repoUsuario.delete(usuario);
                System.out.println("Usuario eliminado");
                mensaje("Usuario eliminado correctamente");
                limpiar();
                break;
        }
    }//GEN-LAST:event_EjectarAccionBotonActionPerformed

    private void buscarUsuario(String text) {
        Optional<Usuario> result = repoUsuario.findById(text);
        if (result.isPresent()) {
            Usuario userFound = result.get();
            System.out.println(userFound.toString());
            ApellidoTexto.setText(userFound.getApellidos());
            NombreTexto.setText(userFound.getNombres());
            EmailTexto.setText(userFound.getEmail());
            CelularTexto.setText(userFound.getCelular());
            FechaNacimientoTexto.setText(userFound.getFecha_n());
            //TO-DO 
        } else {
            String alertaText = "No se ha encontradro un usuario con ese el alias " + text;
            System.out.println(alertaText);
            JOptionPane.showMessageDialog(rootPane, alertaText);

        }

    }

    private void mensaje(String txt) {
        System.out.println(txt);
        JOptionPane.showMessageDialog(rootPane, txt, "", JOptionPane.INFORMATION_MESSAGE);
    }

    private void ActivarCampos(boolean bloqueo) {
        AliasTexto.setEnabled(bloqueo);
        NombreTexto.setEnabled(bloqueo);
        ApellidoTexto.setEnabled(bloqueo);
        AliasTexto.setEnabled(bloqueo);
        FechaNacimientoTexto.setEnabled(bloqueo);
        CelularTexto.setEnabled(bloqueo);
        ContraseñaTexto.setEnabled(bloqueo);
        Contraseña2Texto.setEnabled(bloqueo);
        EmailTexto.setEnabled(bloqueo);
    }

    private void limpiar() {
        AliasTexto.setText("");
        NombreTexto.setText("");
        ApellidoTexto.setText("");
        AliasTexto.setText("");
        FechaNacimientoTexto.setText("");
        CelularTexto.setText("");
        ContraseñaTexto.setText("");
        Contraseña2Texto.setText("");
        EmailTexto.setText("");
    }

    private boolean VerificarContraseña() {
        String contraseña1 = String.valueOf(ContraseñaTexto.getPassword());
        String contraseña2 = String.valueOf(Contraseña2Texto.getPassword());
        return contraseña1.equals(contraseña2);
    }

    private void establecerUsuario() {
        Usuario nuevoUsuario = new Usuario();

        javax.swing.JFormattedTextField[] camposObligatorios = {AliasTexto,
            NombreTexto, ApellidoTexto};

        nuevoUsuario.setAlias(AliasTexto.getText());
        nuevoUsuario.setApellidos(ApellidoTexto.getText());
        nuevoUsuario.setNombres(NombreTexto.getText());
        nuevoUsuario.setCelular(CelularTexto.getText());
        nuevoUsuario.setContraseña(String.valueOf(ContraseñaTexto.getPassword()));
        nuevoUsuario.setEmail(EmailTexto.getText());
        nuevoUsuario.setFecha_n(FechaNacimientoTexto.getText());

        for (javax.swing.JFormattedTextField txt : camposObligatorios) {
            if (txt.getText().isEmpty()) {
                String alertaText = "No se han ingresado los campos requeridos";
                JOptionPane.showMessageDialog(rootPane, alertaText);
                return;
            }
        }

        if (ContraseñaTexto.getPassword().equals("") || ContraseñaTexto.getPassword().length == 0) {
            String alertaText = "No se ingresó contraseña";
            System.out.println(alertaText);
            JOptionPane.showMessageDialog(rootPane, alertaText, "Error en la contraseña", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            repoUsuario.save(nuevoUsuario);
            System.out.println("Usuario establecido correctamente");
            mensaje("Usuario establecido correctamente");
            limpiar();
        } catch (Exception e) {
            String alertaText = "Ocurrió un error al guardar";
            JOptionPane.showMessageDialog(rootPane, alertaText, "Error en el ingreso de "
                    + "un nuevo usuario", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccionSelector;
    private javax.swing.JLabel AliasLabel;
    private javax.swing.JFormattedTextField AliasTexto;
    private javax.swing.JLabel ApellidoLabel;
    private javax.swing.JFormattedTextField ApellidoTexto;
    private javax.swing.JLabel CelularLabel;
    private javax.swing.JFormattedTextField CelularTexto;
    private javax.swing.JLabel Contraseña2Label;
    private javax.swing.JPasswordField Contraseña2Texto;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JPasswordField ContraseñaTexto;
    private javax.swing.JButton EjectarAccionBoton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JFormattedTextField EmailTexto;
    private javax.swing.JLabel FechaNacimientoLabel;
    private javax.swing.JFormattedTextField FechaNacimientoTexto;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JFormattedTextField NombreTexto;
    private javax.swing.JPanel jPanelUsuario;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        ConfigurableApplicationContext ctx = SpringApplication.run(VentanaApp.class, args);

        EventQueue.invokeLater(() -> {
            SpringContext context = new SpringContext();
            context.setApplicationContext(ctx);
            VentanaApp ex = ctx.getBean(VentanaApp.class);
            ex.setVisible(true);
            ex.setRepoUsuario(ctx.getBean(UsuarioRepositorio.class));
        });
    }

}
